package checker

import (
	"testing"
)

// 1. Cloudflare DNS Export (@domain.txt with tabs and Domain header)
func TestParseCloudflareTXT(t *testing.T) {
	sample := `;;
;; Domain:     example.com
;; Exported:   2026-09-27 05:00:00
;;
;; This file is intended for use for informational and debugging
;; purposes only, it should not be substituted for a configuration
;; file.
;;
;; Automatically generated by Cloudflare
;;

;; SOA Record
example.com.	3600	IN	SOA	example.com. dns.cloudflare.com. 2038758814 10000 2400 604800 1800

;; A Records
example.com.	1	IN	A	172.67.180.20
example.com.	1	IN	A	104.21.60.10
api.example.com.	1	IN	A	1.1.1.1

;; CNAME Records
www.example.com.	1	IN	CNAME	example.com.
status.example.com.	1	IN	CNAME	stats.uptimerobot.com.

;; TXT Records
example.com.	1	IN	TXT	"v=spf1 include:_spf.mx.cloudflare.net ~all"
`

	filename := "@example.com.txt"
	res, err := ParseDNSExportFile(filename, []byte(sample))
	if err != nil {
		t.Fatalf("Cloudflare parse failed: %v", err)
	}

	expected := map[string]bool{
		"example.com":        true,
		"api.example.com":    true,
		"www.example.com":    true,
		"status.example.com": true,
	}

	if len(res.Domains) != len(expected) {
		t.Errorf("Expected %d domains, got %d: %v", len(expected), len(res.Domains), res.Domains)
	}
	for _, d := range res.Domains {
		if !expected[d] {
			t.Errorf("Unexpected domain: %s", d)
		}
	}
	if res.FilteredRecords < 2 { // SOA + TXT
		t.Errorf("Expected filtered >= 2, got %d", res.FilteredRecords)
	}
}

// 2. AWS Route 53 (JSON Export)
func TestParseAWSRoute53JSON(t *testing.T) {
	sample := `{
  "ResourceRecordSets": [
    {
      "Name": "example.com.",
      "Type": "A",
      "TTL": 300,
      "ResourceRecords": [{ "Value": "192.0.2.1" }]
    },
    {
      "Name": "app.example.com.",
      "Type": "CNAME",
      "TTL": 300,
      "ResourceRecords": [{ "Value": "lb.amazonaws.com" }]
    },
    {
      "Name": "example.com.",
      "Type": "MX",
      "TTL": 300,
      "ResourceRecords": [{ "Value": "10 mail.example.com" }]
    },
    {
      "Name": "example.com.",
      "Type": "SOA",
      "TTL": 900
    }
  ]
}`

	filename := "route53-records.json"
	res, err := ParseDNSExportFile(filename, []byte(sample))
	if err != nil {
		t.Fatalf("Route53 parse failed: %v", err)
	}

	expected := map[string]bool{
		"example.com":     true,
		"app.example.com": true,
	}
	if len(res.Domains) != len(expected) {
		t.Errorf("Expected %d domains, got %d: %v", len(expected), len(res.Domains), res.Domains)
	}
	if res.FilteredRecords < 2 { // MX + SOA
		t.Errorf("Expected filtered >= 2, got %d", res.FilteredRecords)
	}
}

// 3. 腾讯云 DNSPod (CSV Export)
func TestParseDNSPodCSV(t *testing.T) {
	sample := `主机记录,记录类型,线路类型,记录值,MX优先级,TTL
@,A,默认,1.2.3.4,,600
www,CNAME,默认,example.com,,600
mail,MX,默认,mx.mail.com,10,600
test,TXT,默认,"v=spf1 ~all",,600
`

	filename := "example.com_dnspod.csv"
	res, err := ParseDNSExportFile(filename, []byte(sample))
	if err != nil {
		t.Fatalf("DNSPod CSV parse failed: %v", err)
	}

	expected := map[string]bool{
		"example.com":     true,
		"www.example.com": true,
	}
	if len(res.Domains) != len(expected) {
		t.Errorf("Expected %d domains, got %d: %v", len(expected), len(res.Domains), res.Domains)
	}
}

// 4. 阿里云云解析 DNS (Alibaba Cloud CSV with Domain Column)
func TestParseAliyunCSV(t *testing.T) {
	sample := `域名,主机记录,记录类型,记录值,解析线路,TTL,状态
aliyun.example.com,@,A,114.114.114.114,默认,600,启用
aliyun.example.com,api,CNAME,gateway.aliyun.com,默认,600,启用
aliyun.example.com,mail,MX,mx.aliyun.com,默认,600,启用
`

	filename := "aliyun_dns.csv"
	res, err := ParseDNSExportFile(filename, []byte(sample))
	if err != nil {
		t.Fatalf("Aliyun CSV parse failed: %v", err)
	}

	expected := map[string]bool{
		"aliyun.example.com":     true,
		"api.aliyun.example.com": true,
	}
	if len(res.Domains) != len(expected) {
		t.Errorf("Expected %d domains, got %d: %v", len(expected), len(res.Domains), res.Domains)
	}
}

// 5. GoDaddy (CSV Export)
func TestParseGoDaddyCSV(t *testing.T) {
	sample := `Record type,Name,Value,TTL
A,@,198.51.100.1,600
CNAME,portal,example.org,3600
MX,@,mail.example.org,3600
TXT,@,"test-verification",3600
`

	filename := "example.org.csv"
	res, err := ParseDNSExportFile(filename, []byte(sample))
	if err != nil {
		t.Fatalf("GoDaddy CSV parse failed: %v", err)
	}

	expected := map[string]bool{
		"example.org":        true,
		"portal.example.org": true,
	}
	if len(res.Domains) != len(expected) {
		t.Errorf("Expected %d domains, got %d: %v", len(expected), len(res.Domains), res.Domains)
	}
}

// 6. Namecheap (CSV Export)
func TestParseNamecheapCSV(t *testing.T) {
	sample := `Host,Type,Target,TTL
@,A,203.0.113.1,1800
blog,CNAME,hashnode.network,1800
@,TXT,"v=spf1 ~all",1800
`

	filename := "myzone.net.csv"
	res, err := ParseDNSExportFile(filename, []byte(sample))
	if err != nil {
		t.Fatalf("Namecheap CSV parse failed: %v", err)
	}

	expected := map[string]bool{
		"myzone.net":      true,
		"blog.myzone.net": true,
	}
	if len(res.Domains) != len(expected) {
		t.Errorf("Expected %d domains, got %d: %v", len(expected), len(res.Domains), res.Domains)
	}
}

// 7. Hurricane Electric (HE.net) / BIND 9 / Google Cloud DNS ($ORIGIN Zone)
func TestParseStandardBINDZone(t *testing.T) {
	sample := `; BIND Zone File for he-domain.com
$ORIGIN he-domain.com.
$TTL 86400

@       IN      SOA     ns1.he.net. hostmaster.he.net. ( 2026092701 86400 7200 3600000 86400 )
        IN      NS      ns1.he.net.
        IN      NS      ns2.he.net.

@       IN      A       192.0.2.10
www     IN      CNAME   he-domain.com.
cdn     300     IN      CNAME   fastly.net.
mail    IN      MX      10 mail.he-domain.com.
`

	filename := "he-domain.com.zone"
	res, err := ParseDNSExportFile(filename, []byte(sample))
	if err != nil {
		t.Fatalf("HE.net BIND Zone parse failed: %v", err)
	}

	expected := map[string]bool{
		"he-domain.com":     true,
		"www.he-domain.com": true,
		"cdn.he-domain.com": true,
	}
	if len(res.Domains) != len(expected) {
		t.Errorf("Expected %d domains, got %d: %v", len(expected), len(res.Domains), res.Domains)
	}
	if res.FilteredRecords < 4 { // SOA, NS, NS, MX
		t.Errorf("Expected filtered >= 4, got %d", res.FilteredRecords)
	}
}
